.section .text


#####################################################################
#  Exception 0 Entry
#
#  The entry point for the Exception 0 handler.
#####################################################################
.global __exception0_entry
.type __exception0_entry, @function
__exception0_entry:
	pusha
	# call __exception0_handler
	popa
	iret

#####################################################################
#  Exception 1 Entry
#
#  The entry point for the Exception 1 handler.
#####################################################################
.global __exception1_entry
.type __exception1_entry, @function
__exception1_entry:
	pusha
	# call __exception1_handler
	popa
	iret

#####################################################################
#  Exception 2 Entry
#
#  The entry point for the Exception 2 handler.
#####################################################################
.global __exception2_entry
.type __exception2_entry, @function
__exception2_entry:
	pusha
	# call __exception2_handler
	popa
	iret

#####################################################################
#  Exception 3 Entry
#
#  The entry point for the Exception 3 handler.
#####################################################################
.global __exception3_entry
.type __exception3_entry, @function
__exception3_entry:
	pusha
	# call __exception3_handler
	popa
	iret

#####################################################################
#  Exception 4 Entry
#
#  The entry point for the Exception 4 handler.
#####################################################################
.global __exception4_entry
.type __exception4_entry, @function
__exception4_entry:
	pusha
	# call __exception4_handler
	popa
	iret

#####################################################################
#  Exception 5 Entry
#
#  The entry point for the Exception 5 handler.
#####################################################################
.global __exception5_entry
.type __exception5_entry, @function
__exception5_entry:
	pusha
	# call __exception5_handler
	popa
	iret

#####################################################################
#  Exception 6 Entry
#
#  The entry point for the Exception 6 handler.
#####################################################################
.global __exception6_entry
.type __exception6_entry, @function
__exception6_entry:
	pusha
	# call __exception6_handler
	popa
	iret

#####################################################################
#  Exception 7 Entry
#
#  The entry point for the Exception 7 handler.
#####################################################################
.global __exception7_entry
.type __exception7_entry, @function
__exception7_entry:
	pusha
	# call __exception7_handler
	popa
	iret

#####################################################################
#  Exception 8 Entry
#
#  The entry point for the Exception 8 handler.
#####################################################################
.global __exception8_entry
.type __exception8_entry, @function
__exception8_entry:
	pusha
	# call __exception8_handler
	popa
	iret

#####################################################################
#  Exception 9 Entry
#
#  The entry point for the Exception 9 handler.
#####################################################################
.global __exception9_entry
.type __exception9_entry, @function
__exception9_entry:
	pusha
	# call __exception9_handler
	popa
	iret

#####################################################################
#  Exception 10 Entry
#
#  The entry point for the Exception 10 handler.
#####################################################################
.global __exception10_entry
.type __exception10_entry, @function
__exception10_entry:
	pusha
	# call __exception10_handler
	popa
	iret

#####################################################################
#  Exception 11 Entry
#
#  The entry point for the Exception 11 handler.
#####################################################################
.global __exception11_entry
.type __exception11_entry, @function
__exception11_entry:
	pusha
	# call __exception11_handler
	popa
	iret

#####################################################################
#  Exception 12 Entry
#
#  The entry point for the Exception 12 handler.
#####################################################################
.global __exception12_entry
.type __exception12_entry, @function
__exception12_entry:
	pusha
	# call __exception12_handler
	popa
	iret

#####################################################################
#  Exception 13 Entry
#
#  The entry point for the Exception 13 handler.
#####################################################################
.global __exception13_entry
.type __exception13_entry, @function
__exception13_entry:
	pusha
	# call __exception13_handler
	popa
	iret

#####################################################################
#  Exception 14 Entry
#
#  The entry point for the Exception 14 handler.
#####################################################################
.global __exception14_entry
.type __exception14_entry, @function
__exception14_entry:
	pusha
	# call __exception14_handler
	popa
	iret

#####################################################################
#  Exception 15 Entry
#
#  The entry point for the Exception 15 handler.
#####################################################################
.global __exception15_entry
.type __exception15_entry, @function
__exception15_entry:
	pusha
	# call __exception15_handler
	popa
	iret

#####################################################################
#  Exception 16 Entry
#
#  The entry point for the Exception 16 handler.
#####################################################################
.global __exception16_entry
.type __exception16_entry, @function
__exception16_entry:
	pusha
	# call __exception16_handler
	popa
	iret

#####################################################################
#  Exception 17 Entry
#
#  The entry point for the Exception 17 handler.
#####################################################################
.global __exception17_entry
.type __exception17_entry, @function
__exception17_entry:
	pusha
	# call __exception17_handler
	popa
	iret

#####################################################################
#  Exception 18 Entry
#
#  The entry point for the Exception 18 handler.
#####################################################################
.global __exception18_entry
.type __exception18_entry, @function
__exception18_entry:
	pusha
	# call __exception18_handler
	popa
	iret

#####################################################################
#  Exception 19 Entry
#
#  The entry point for the Exception 19 handler.
#####################################################################
.global __exception19_entry
.type __exception19_entry, @function
__exception19_entry:
	pusha
	# call __exception19_handler
	popa
	iret

#####################################################################
#  Exception 20 Entry
#
#  The entry point for the Exception 20 handler.
#####################################################################
.global __exception20_entry
.type __exception20_entry, @function
__exception20_entry:
	pusha
	# call __exception20_handler
	popa
	iret

#####################################################################
#  Exception 21 Entry
#
#  The entry point for the Exception 21 handler.
#####################################################################
.global __exception21_entry
.type __exception21_entry, @function
__exception21_entry:
	pusha
	# call __exception21_handler
	popa
	iret

#####################################################################
#  Exception 22 Entry
#
#  The entry point for the Exception 22 handler.
#####################################################################
.global __exception22_entry
.type __exception22_entry, @function
__exception22_entry:
	pusha
	# call __exception22_handler
	popa
	iret

#####################################################################
#  Exception 23 Entry
#
#  The entry point for the Exception 23 handler.
#####################################################################
.global __exception23_entry
.type __exception23_entry, @function
__exception23_entry:
	pusha
	# call __exception23_handler
	popa
	iret

#####################################################################
#  Exception 24 Entry
#
#  The entry point for the Exception 24 handler.
#####################################################################
.global __exception24_entry
.type __exception24_entry, @function
__exception24_entry:
	pusha
	# call __exception24_handler
	popa
	iret

#####################################################################
#  Exception 25 Entry
#
#  The entry point for the Exception 25 handler.
#####################################################################
.global __exception25_entry
.type __exception25_entry, @function
__exception25_entry:
	pusha
	# call __exception25_handler
	popa
	iret

#####################################################################
#  Exception 26 Entry
#
#  The entry point for the Exception 26 handler.
#####################################################################
.global __exception26_entry
.type __exception26_entry, @function
__exception26_entry:
	pusha
	# call __exception26_handler
	popa
	iret

#####################################################################
#  Exception 27 Entry
#
#  The entry point for the Exception 27 handler.
#####################################################################
.global __exception27_entry
.type __exception27_entry, @function
__exception27_entry:
	pusha
	# call __exception27_handler
	popa
	iret

#####################################################################
#  Exception 28 Entry
#
#  The entry point for the Exception 28 handler.
#####################################################################
.global __exception28_entry
.type __exception28_entry, @function
__exception28_entry:
	pusha
	# call __exception28_handler
	popa
	iret

#####################################################################
#  Exception 29 Entry
#
#  The entry point for the Exception 29 handler.
#####################################################################
.global __exception29_entry
.type __exception29_entry, @function
__exception29_entry:
	pusha
	# call __exception29_handler
	popa
	iret

#####################################################################
#  Exception 30 Entry
#
#  The entry point for the Exception 30 handler.
#####################################################################
.global __exception30_entry
.type __exception30_entry, @function
__exception30_entry:
	pusha
	# call __exception30_handler
	popa
	iret

#####################################################################
#  Exception 31 Entry
#
#  The entry point for the Exception 31 handler.
#####################################################################
.global __exception31_entry
.type __exception31_entry, @function
__exception31_entry:
	pusha
	# call __exception31_handler
	popa
	iret

