-------------------------------------------------------------------------------
--  Copyright (c) 2019, CXOS.
--  This program is free software; you can redistribute it and/or modify it
--  under the terms of the GNU General Public License as published by the
--  Free Software Foundation; either version 3 of the License, or
--  (at your option) any later version.
--
--  Authors:
--     Anthony <ajxs [at] panoptic.online>
-------------------------------------------------------------------------------

package body x86.Time_Keeping is
   ----------------------------------------------------------------------------
   --  Clock
   ----------------------------------------------------------------------------
   function Clock return Time is
   begin
      return System_Time;
   end Clock;

   ----------------------------------------------------------------------------
   --  Initialise
   --
   --  Implementation Notes:
   --   - Sets the system internal clock to 0.
   ----------------------------------------------------------------------------
   procedure Initialise is
   begin
      System_Time := 0;
   end Initialise;

   ----------------------------------------------------------------------------
   --  System_Tick_Handler
   --
   --  Implementation Notes:
   --   - Handles an individual system 'tick' generated by the system's
   --     Programmable Interval Timer. Each call to this function will
   --     increment the internal timer by the predefined timer interval.
   ----------------------------------------------------------------------------
   procedure System_Tick_Handler is
   begin
      System_Time := System_Time + SYSTEM_TICK_PERIOD;
   end System_Tick_Handler;

end x86.Time_Keeping;
